// Generated by scripts/gen-demo.py — do not edit by hand.
// These are real `termdoc` renderings of scripts/sample.md, not mock-ups.

export const demoAnsi = `<span class="b ansi-bright-blue">Release notes</span>

A <span class="b">universal</span> document viewer for the <span class="i">terminal</span>, with <span class="ansi-bright-yellow">inline code</span>
and a <span class="u ansi-bright-blue">link</span><span class="dim ansi-blue">[1]</span>.

<span class="b ansi-bright-cyan">Formats</span>

<span class="ansi-bright-cyan">• </span>Markdown, plain text and logs
<span class="ansi-bright-cyan">• </span>Detection for JSON, YAML, TOML, XML, CSV
  <span class="ansi-bright-cyan">◦ </span>and the Office/ZIP family
<span class="ansi-bright-cyan">• </span>PDF and EPUB are on the roadmap

<span class="ansi-bright-black">┌──────────┬──────────┬───────────┐</span>
<span class="ansi-bright-black">│</span> <span class="b">Format</span>   <span class="ansi-bright-black">│</span>  <span class="b">Status</span>  <span class="ansi-bright-black">│</span> <span class="b">Milestone</span> <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">├──────────┼──────────┼───────────┤</span>
<span class="ansi-bright-black">│</span> Markdown <span class="ansi-bright-black">│</span>  ready   <span class="ansi-bright-black">│</span> M0        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> CSV      <span class="ansi-bright-black">│</span> detected <span class="ansi-bright-black">│</span> M1        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> PDF      <span class="ansi-bright-black">│</span> pending  <span class="ansi-bright-black">│</span> M3        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">└──────────┴──────────┴───────────┘</span>

<span class="ansi-bright-yellow">fn main() {</span>
<span class="ansi-bright-yellow">    println!(&quot;hello&quot;);</span>
<span class="ansi-bright-yellow">}</span>

<span class="ansi-bright-black">│</span> <span class="dim i">Streaming by default: a 488 MB log costs 1.4 MB of memory.</span>

<span class="dim ansi-blue">[1] https://termdoc.app</span>`

export const rungUnicode = `<span class="b ansi-bright-blue">Release notes</span>

A <span class="b">universal</span> document viewer for the <span class="i">terminal</span>
, with <span class="ansi-bright-yellow">inline code</span> and a <span class="u ansi-bright-blue">link</span><span class="dim ansi-blue">[1]</span>.

<span class="b ansi-bright-cyan">Formats</span>

<span class="ansi-bright-cyan">• </span>Markdown, plain text and logs
<span class="ansi-bright-cyan">• </span>Detection for JSON, YAML, TOML, XML, CSV
  <span class="ansi-bright-cyan">◦ </span>and the Office/ZIP family
<span class="ansi-bright-cyan">• </span>PDF and EPUB are on the roadmap

<span class="ansi-bright-black">┌──────────┬──────────┬───────────┐</span>
<span class="ansi-bright-black">│</span> <span class="b">Format</span>   <span class="ansi-bright-black">│</span>  <span class="b">Status</span>  <span class="ansi-bright-black">│</span> <span class="b">Milestone</span> <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">├──────────┼──────────┼───────────┤</span>
<span class="ansi-bright-black">│</span> Markdown <span class="ansi-bright-black">│</span>  ready   <span class="ansi-bright-black">│</span> M0        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> CSV      <span class="ansi-bright-black">│</span> detected <span class="ansi-bright-black">│</span> M1        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> PDF      <span class="ansi-bright-black">│</span> pending  <span class="ansi-bright-black">│</span> M3        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">└──────────┴──────────┴───────────┘</span>

<span class="ansi-bright-yellow">fn main() {</span>
<span class="ansi-bright-yellow">    println!(&quot;hello&quot;);</span>
<span class="ansi-bright-yellow">}</span>

<span class="ansi-bright-black">│</span> <span class="dim i">Streaming by default: a 488 MB log costs</span>
<span class="ansi-bright-black">│</span> <span class="dim i">1.4 MB of memory.</span>

<span class="dim ansi-blue">[1] https://termdoc.app</span>`

export const rungAscii = `<span class="b ansi-bright-blue">Release notes</span>

A <span class="b">universal</span> document viewer for the <span class="i">terminal</span>
, with <span class="ansi-bright-yellow">inline code</span> and a <span class="u ansi-bright-blue">link</span><span class="dim ansi-blue">[1]</span>.

<span class="b ansi-bright-cyan">Formats</span>

<span class="ansi-bright-cyan">* </span>Markdown, plain text and logs
<span class="ansi-bright-cyan">* </span>Detection for JSON, YAML, TOML, XML, CSV
  <span class="ansi-bright-cyan">- </span>and the Office/ZIP family
<span class="ansi-bright-cyan">* </span>PDF and EPUB are on the roadmap

<span class="ansi-bright-black">+----------+----------+-----------+</span>
<span class="ansi-bright-black">|</span> <span class="b">Format</span>   <span class="ansi-bright-black">|</span>  <span class="b">Status</span>  <span class="ansi-bright-black">|</span> <span class="b">Milestone</span> <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">+----------+----------+-----------+</span>
<span class="ansi-bright-black">|</span> Markdown <span class="ansi-bright-black">|</span>  ready   <span class="ansi-bright-black">|</span> M0        <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">|</span> CSV      <span class="ansi-bright-black">|</span> detected <span class="ansi-bright-black">|</span> M1        <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">|</span> PDF      <span class="ansi-bright-black">|</span> pending  <span class="ansi-bright-black">|</span> M3        <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">+----------+----------+-----------+</span>

<span class="ansi-bright-yellow">fn main() {</span>
<span class="ansi-bright-yellow">    println!(&quot;hello&quot;);</span>
<span class="ansi-bright-yellow">}</span>

<span class="ansi-bright-black">|</span> <span class="dim i">Streaming by default: a 488 MB log costs</span>
<span class="ansi-bright-black">|</span> <span class="dim i">1.4 MB of memory.</span>

<span class="dim ansi-blue">[1] https://termdoc.app</span>`

export const rungPlain = `# Release notes

A universal document viewer for the terminal
, with inline code and a link[1].

## Formats

* Markdown, plain text and logs
* Detection for JSON, YAML, TOML, XML, CSV
  - and the Office/ZIP family
* PDF and EPUB are on the roadmap

+----------+----------+-----------+
| Format   |  Status  | Milestone |
+----------+----------+-----------+
| Markdown |  ready   | M0        |
| CSV      | detected | M1        |
| PDF      | pending  | M3        |
+----------+----------+-----------+

fn main() {
    println!(&quot;hello&quot;);
}

| Streaming by default: a 488 MB log costs
| 1.4 MB of memory.

[1] https://termdoc.app`
