// Generated by scripts/gen-demo.py — do not edit by hand.
// These are real `termdoc` renderings of scripts/sample.md, not mock-ups.

export const demoAnsi = `<span class="b ansi-bright-blue">Release notes</span>

A <span class="b">fast</span>, terminal-native document viewer, with <span class="ansi-bright-yellow">inline code</span> and
a <span class="u ansi-bright-blue">link</span><span class="dim ansi-blue">[1]</span>.

<span class="b ansi-bright-cyan">Formats</span>

<span class="ansi-bright-cyan">• </span>Markdown, plain text, logs, data files and source code
<span class="ansi-bright-cyan">• </span>Detection for HTML, PDF and the Office family
  <span class="ansi-bright-cyan">◦ </span>and the Office/ZIP family
<span class="ansi-bright-cyan">• </span>PDF and EPUB are on the roadmap

<span class="ansi-bright-black">┌──────────┬──────────┬───────────┐</span>
<span class="ansi-bright-black">│</span> <span class="b">Format</span>   <span class="ansi-bright-black">│</span>  <span class="b">Status</span>  <span class="ansi-bright-black">│</span> <span class="b">Milestone</span> <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">├──────────┼──────────┼───────────┤</span>
<span class="ansi-bright-black">│</span> Markdown <span class="ansi-bright-black">│</span>  ready   <span class="ansi-bright-black">│</span> M0        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> HTML     <span class="ansi-bright-black">│</span> detected <span class="ansi-bright-black">│</span> M3        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> PDF      <span class="ansi-bright-black">│</span> pending  <span class="ansi-bright-black">│</span> M3        <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">└──────────┴──────────┴───────────┘</span>

<span class="ansi-magenta">fn</span> <span class="ansi-bright-blue">main</span><span class="ansi-bright-black">()</span> <span class="ansi-bright-black">{</span>
    println!<span class="ansi-bright-black">(</span><span class="ansi-green">&quot;hello&quot;</span><span class="ansi-bright-black">);</span>
<span class="ansi-bright-black">}</span>

<span class="ansi-bright-black">│</span> <span class="dim i">Streaming by default: a 488 MB log costs 1.4 MB of memory.</span>

<span class="dim ansi-blue">[1] https://termdoc.app</span>`

export const rungBox = `<span class="ansi-bright-black">┌──────────┬──────────┬─────┐</span>
<span class="ansi-bright-black">│</span> <span class="b">Format</span>   <span class="ansi-bright-black">│</span>  <span class="b">Status</span>  <span class="ansi-bright-black">│</span> <span class="b">M</span>   <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">├──────────┼──────────┼─────┤</span>
<span class="ansi-bright-black">│</span> Markdown <span class="ansi-bright-black">│</span>  ready   <span class="ansi-bright-black">│</span> M0  <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> HTML     <span class="ansi-bright-black">│</span> detected <span class="ansi-bright-black">│</span> M3  <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">│</span> PDF      <span class="ansi-bright-black">│</span> pending  <span class="ansi-bright-black">│</span> M3  <span class="ansi-bright-black">│</span>
<span class="ansi-bright-black">└──────────┴──────────┴─────┘</span>`

export const rungAscii = `<span class="ansi-bright-black">+----------+----------+-----+</span>
<span class="ansi-bright-black">|</span> <span class="b">Format</span>   <span class="ansi-bright-black">|</span>  <span class="b">Status</span>  <span class="ansi-bright-black">|</span> <span class="b">M</span>   <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">+----------+----------+-----+</span>
<span class="ansi-bright-black">|</span> Markdown <span class="ansi-bright-black">|</span>  ready   <span class="ansi-bright-black">|</span> M0  <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">|</span> HTML     <span class="ansi-bright-black">|</span> detected <span class="ansi-bright-black">|</span> M3  <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">|</span> PDF      <span class="ansi-bright-black">|</span> pending  <span class="ansi-bright-black">|</span> M3  <span class="ansi-bright-black">|</span>
<span class="ansi-bright-black">+----------+----------+-----+</span>`

export const rungTsv = `Format	Status	M
Markdown	ready	M0
HTML	detected	M3
PDF	pending	M3`
