import { demoAnsi, rungUnicode, rungAscii, rungPlain } from './demo'

const GITHUB = 'https://github.com/marturojt/termdoc'
const CRATES = 'https://crates.io/crates/termdoc'

const installHtml = `<span class="comment"># from crates.io</span>
<span class="prompt">$</span> cargo install <a href="${CRATES}" class="code-link">termdoc</a>

<span class="comment"># then point it at anything</span>
<span class="prompt">$</span> termdoc README.md
<span class="prompt">$</span> termdoc --explain odd.dat
<span class="prompt">$</span> cat README.md | termdoc

<span class="comment"># Homebrew, AUR, Scoop, static binaries — planned</span>`

function Bar({ filled }: { filled: number }) {
  const total = 10
  return (
    <span className="ms-bar">
      <span className="on">{'█'.repeat(filled)}</span>
      {'░'.repeat(total - filled)}
    </span>
  )
}

export default function Home() {
  return (
    <div className="page">
      <header className="hero">
        <h1 className="hero-title">termdoc</h1>
        <p className="hero-tagline">A universal document viewer for the terminal</p>
        <p className="hero-sub">
          It is not an editor. It is not a converter. It is not an IDE.
        </p>
        <nav className="hero-links">
          <a className="btn" href={GITHUB}>GitHub</a>
          <a className="btn" href={CRATES}>crates.io</a>
          <a className="btn" href="#install">Install</a>
        </nav>
        <span className="status-chip">v0.1.0 · M0 complete · M1 in progress</span>
      </header>

      <section id="output">
        <h2 className="section-title">what it looks like</h2>
        <div className="term">
          <pre dangerouslySetInnerHTML={{ __html: demoAnsi }} />
        </div>
        <p className="section-note">
          Not a mock-up. That block is generated by running <code>termdoc</code> over a
          Markdown file and translating the ANSI it emits — the colours, the wrapping and
          the box-drawing are the renderer&rsquo;s own.
        </p>
      </section>

      <section id="degradation">
        <h2 className="section-title">graceful degradation</h2>
        <div className="rungs">
          <div>
            <div className="rung-label">unicode + colour</div>
            <div className="term">
              <pre dangerouslySetInnerHTML={{ __html: rungUnicode }} />
            </div>
          </div>
          <div>
            <div className="rung-label">--ascii</div>
            <div className="term">
              <pre dangerouslySetInnerHTML={{ __html: rungAscii }} />
            </div>
          </div>
          <div>
            <div className="rung-label">no colour, no unicode</div>
            <div className="term">
              <pre dangerouslySetInnerHTML={{ __html: rungPlain }} />
            </div>
          </div>
        </div>
        <p className="section-note">
          The same document, three rungs down. Degradation is an input to the layout, not a
          chain of special cases bolted onto it: the terminal&rsquo;s real capabilities are
          detected once and every ladder — colour, box-drawing, hyperlinks, headings — reads
          from that. With colour off, not one escape byte is emitted.
        </p>
      </section>

      <section id="features">
        <h2 className="section-title">features</h2>
        <ul className="features">
          <li><strong>Streaming by design</strong> — the document is an event stream borrowing from an <code>mmap</code>, never a materialised tree. A 488&nbsp;MB log costs 1.4&nbsp;MB of memory</li>
          <li><strong>Behaves like a system utility</strong> — <code>termdoc huge.log | head -5</code> dies with signal 13 like <code>cat</code> does, instead of panicking. In a pipe, stdout carries only the document</li>
          <li><strong>Unicode-aware layout</strong> — grapheme clusters, CJK widths, combining marks and ZWJ sequences. No line exceeds the width in display cells, and none ends in trailing spaces</li>
          <li><strong>Layered detection</strong> — magic bytes, extension, structure and delimiter sniffing each propose a format with a confidence and a reason. <code>termdoc --explain</code> prints every opinion, including the losing ones</li>
          <li><strong>Encoding resolved once</strong> — BOM, then UTF-8 validation, then statistical detection. A latin-1 file renders with its accents, and no reader ever decides how bytes become text</li>
          <li><strong>Tables that fit</strong> — width allocated across columns, degrading box-drawing → ASCII → TSV rather than truncating data</li>
          <li><strong>Architecture enforced by the compiler</strong> — a reader cannot see a backend, because Cargo&rsquo;s dependency graph does not contain that edge. A test reads the manifests and fails if one appears</li>
          <li><strong>MIT OR Apache-2.0</strong> — no telemetry, no network calls, no lock-in</li>
        </ul>
      </section>

      <section id="install">
        <h2 className="section-title">install</h2>
        <div className="install-block">
          <pre dangerouslySetInnerHTML={{ __html: installHtml }} />
        </div>
        <p className="install-note">
          Requires a Rust toolchain (<a href="https://rustup.rs">rustup.rs</a>). Prebuilt
          binaries and a Homebrew tap are on the backlog. Runs on Linux, macOS and Windows —
          all three are covered by CI.
        </p>
      </section>

      <section id="not">
        <h2 className="section-title">what termdoc is not</h2>
        <ul className="not-list">
          <li>Not an editor — it never writes to the document</li>
          <li>Not a converter, though a Markdown backend is planned for piping</li>
          <li>Not an IDE, and not a syntax-highlighting playground</li>
          <li>It never shells out to an external application to display a file</li>
          <li>No telemetry, no analytics, no network calls of any kind</li>
        </ul>
      </section>

      <section id="status">
        <h2 className="section-title">status</h2>
        <ul className="milestones">
          <li><span className="ms-id">M0</span><Bar filled={10} /><span className="ms-desc">Markdown, plain text, logs — complete</span></li>
          <li><span className="ms-id">M1</span><Bar filled={3} /><span className="ms-desc">data and code: detection and encoding landed, readers next</span></li>
          <li><span className="ms-id">M2</span><Bar filled={0} /><span className="ms-desc">the interactive pager</span></li>
          <li><span className="ms-id">M3</span><Bar filled={0} /><span className="ms-desc">HTML, DOCX, ODT, RTF, EPUB, PDF, images</span></li>
          <li><span className="ms-id">M4</span><Bar filled={0} /><span className="ms-desc">plugin host and SDK</span></li>
          <li><span className="ms-id">M5</span><Bar filled={0} /><span className="ms-desc">PPTX, XLSX, Jupyter, SVG, math</span></li>
        </ul>

        <div className="metrics">
          <div>
            <span className="metric-value">3.9 ms</span>
            <span className="metric-label">startup</span>
          </div>
          <div>
            <span className="metric-value">1.4 MB</span>
            <span className="metric-label">memory · 488 MB input</span>
          </div>
          <div>
            <span className="metric-value">258</span>
            <span className="metric-label">tests, 3 platforms</span>
          </div>
        </div>

        <p className="status-text">
          Readers exist for Markdown, plain text and logs. Detection recognises considerably
          more — JSON, YAML, TOML, XML, HTML, CSV, source code, PDF and the Office/ZIP family
          — and until each dedicated reader lands, a recognised-but-unreadable text format is
          shown as plain text with a warning on stderr. <code>--strict</code> turns that
          warning into an error.
        </p>

        <a className="backlog-link" href={`${GITHUB}/blob/main/docs/DESIGN.md`}>
          → design document
        </a>
        {' '}
        <a className="backlog-link" href={`${GITHUB}/blob/main/docs/HANDOFF.md`}>
          → roadmap and backlog
        </a>
      </section>

      <footer>
        <div className="footer-links">
          <a href={GITHUB}>GitHub</a>
          <a href={CRATES}>crates.io</a>
          <a href="https://docs.rs/termdoc-core">docs.rs</a>
          <a href={`${GITHUB}/blob/main/LICENSE-MIT`}>MIT OR Apache-2.0</a>
        </div>
        <span className="footer-build">termdoc.app</span>
      </footer>
    </div>
  )
}
