#!/usr/bin/env python3
"""Turns real `termdoc` output into the HTML the site renders.

The demo blocks on termdoc.app are not mock-ups. This script runs the actual
binary over scripts/sample.md and translates the ANSI it emits into spans, so
what the page shows is exactly what a terminal shows. If the renderer's colours
or glyphs change, re-run this and the site changes with them.

    python3 scripts/gen-demo.py            # termdoc from PATH
    TERMDOC=../termdoc/target/release/termdoc python3 scripts/gen-demo.py

Writes app/demo.ts.
"""

import html
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SAMPLE = ROOT / "scripts" / "sample.md"
# The ladder uses a table on its own. On a whole document the difference between
# box-drawing and ASCII is a few glyphs lost in a wall of prose; on a table it is
# the entire frame, and the bottom rung — giving up the frame for tab-separated
# values rather than truncating a cell — is only visible here.
TABLE = ROOT / "scripts" / "table.md"
OUT = ROOT / "app" / "demo.ts"
TERMDOC = os.environ.get("TERMDOC", "termdoc")

# The SGR parameters termdoc actually emits. Anything outside this table is a
# signal that the renderer grew a new style and this script needs updating,
# rather than something to silently drop.
COLORS = {
    "30": "ansi-black",   "31": "ansi-red",     "32": "ansi-green",
    "33": "ansi-yellow",  "34": "ansi-blue",    "35": "ansi-magenta",
    "36": "ansi-cyan",    "37": "ansi-white",
    "90": "ansi-bright-black",   "91": "ansi-bright-red",
    "92": "ansi-bright-green",   "93": "ansi-bright-yellow",
    "94": "ansi-bright-blue",    "95": "ansi-bright-magenta",
    "96": "ansi-bright-cyan",    "97": "ansi-bright-white",
}
ATTRS = {"1": "b", "2": "dim", "3": "i", "4": "u"}

SGR = re.compile(r"\x1b\[([0-9;]*)m")


def render(args, doc=SAMPLE):
    """Runs termdoc and returns its stdout, or exits with a useful message."""
    try:
        proc = subprocess.run(
            [TERMDOC, *args, str(doc)],
            capture_output=True, text=True, check=True,
        )
    except FileNotFoundError:
        sys.exit(
            f"could not run '{TERMDOC}'.\n"
            "Install it with `cargo install termdoc`, or point TERMDOC at a build."
        )
    except subprocess.CalledProcessError as e:
        sys.exit(f"termdoc failed: {e.stderr.strip()}")
    return proc.stdout


def to_html(text):
    """ANSI -> spans. Emits one span per styled run; unstyled text stays bare."""
    out = []
    classes = []
    pos = 0
    open_span = False

    def close():
        nonlocal open_span
        if open_span:
            out.append("</span>")
            open_span = False

    for m in SGR.finditer(text):
        chunk = text[pos:m.start()]
        if chunk:
            out.append(html.escape(chunk))
        pos = m.end()

        params = [p for p in m.group(1).split(";") if p != ""]
        # An empty parameter list means SGR 0: reset.
        if not params:
            params = ["0"]

        close()
        for p in params:
            if p == "0":
                classes = []
            elif p in ATTRS:
                classes.append(ATTRS[p])
            elif p in COLORS:
                classes.append(COLORS[p])
            else:
                sys.exit(
                    f"unknown SGR parameter {p!r} in termdoc's output.\n"
                    "The renderer emits a style this script does not map yet."
                )
        if classes:
            out.append(f'<span class="{" ".join(classes)}">')
            open_span = True

    tail = text[pos:]
    if tail:
        out.append(html.escape(tail))
    close()
    return "".join(out).rstrip("\n")


def ts_literal(s):
    return "`" + s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${") + "`"


def main():
    blocks = {
        # The headline demo: what you actually see in a colour terminal.
        "demoAnsi": to_html(render(["--color", "always", "--width", "62"])),
        # The ladder: the same table, each rung giving up something the one above
        # it could afford. The last one gives up the frame entirely rather than
        # truncate a cell, because that output is for `cut` and `awk`.
        "rungBox": to_html(render(["--color", "always", "--width", "32"], TABLE)),
        "rungAscii": to_html(render(["--color", "always", "--ascii", "--width", "32"], TABLE)),
        "rungTsv": to_html(render(["--color", "always", "--width", "18"], TABLE)),
    }

    body = [
        "// Generated by scripts/gen-demo.py — do not edit by hand.",
        "// These are real `termdoc` renderings of scripts/sample.md, not mock-ups.",
        "",
    ]
    for name, value in blocks.items():
        body.append(f"export const {name} = {ts_literal(value)}\n")

    OUT.write_text("\n".join(body))
    print(f"wrote {OUT.relative_to(ROOT)}  ({sum(len(v) for v in blocks.values())} chars of HTML)")


if __name__ == "__main__":
    main()
